[build]
  base = "."
  command = "npm run build"
  publish = ".next"

[site]
  name = "megansmunchies"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js handles its own routing, so we don't need the redirect rule
# that would be used for single-page applications

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

